version: "3.8"

services:
  excalidraw-storage-backend:
    build: 
      context: .
      target: production
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    environment:
      STORAGE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      ENABLE_S3_BACKEND: ${ENABLE_S3_BACKEND}
      EXCALIDRAW_S3_BUCKET_NAME: ${EXCALIDRAW_S3_BUCKET_NAME}
      EXCALIDRAW_S3_ACCESS_KEY_ID: ${EXCALIDRAW_S3_ACCESS_KEY_ID}
      EXCALIDRAW_S3_SECRET_ACCESS_KEY: ${EXCALIDRAW_S3_SECRET_ACCESS_KEY}
    volumes:
      - .:/home/node/app

volumes:
  postgres_data: